flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import render_template, request, Blueprint, current_app, Response,redirect, url_for
from flaskblog.models import Post
from flask_login import current_user
from flaskblog.main.forms import SettingForm
from datetime import date

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    if current_user.is_authenticated:
        sidebar_info = []
        sidebar_info.append(f"Hi {current_user.username} !")
        sidebar_info.append(f'You have been here for {(date.today() - current_user.date_created).days + 1} days')
        sidebar_info.append('Share your life by writting a post !')
        return render_template('home.html', posts=posts, sidebar_info=sidebar_info)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route("/settings", methods=['GET', 'POST'])
def settings():
    settings = SettingForm()
    sidebar_info = ['Modify the color of your web !']
    return render_template('settings.html', title='Settings', form = settings, legend = "Settings", sidebar_info = sidebar_info)

@main.route("/favicon.ico")
def get_fav():
    return url_for('static', filename="icons/favicon.ico")

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, current_app)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        current_app.logger.info(f'Post created: {post}')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post',
                           sidebar_info = ['Create a new post !', 'Don\' leave the form empty '])


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        current_app.logger.info(f'Post updated: {post}')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    current_app.logger.info(f"Post deleted: {post}")
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email
from datetime import date

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        current_app.logger.info(f"Account created: {user}")
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            current_app.logger.info(f'user log in: {current_user}')
            flash("Login successfully", 'info')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
            current_app.logger.warn(f"unsuccessful login {form.email.data}")
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    current_app.logger.info(f"user log out: {current_user}")
    logout_user()
    flash('Successfully Logout !', 'info')
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form,
                           sidebar_info = ['Change this form to update your Info', 'You can also updated your image'])


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}

    <!--posts-->
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body article-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            <!--controls, such as like buttons, comments, and collection-->
            <div>
                <span class="btn btn-info like" ref="{{post.id}}">
                    like
                    <span id="like_count{{post.id}}" >{{post.likes}}</span>
                </span>
                
                <button type="button" class="btn btn-primary btn-info comment-btn" ref="{{post.id}}" data-toggle="modal" data-target="#modal{{post.id}}">
                    Comments
                </button>

                <div class="modal fade" id="modal{{post.id}}" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body" id="comment-list-{{post.id}}">
                            </div>
                            <div class="modal-footer">
                                <form style="width: 60%" id="comment-form-{{post.id}}">
                                    <!-- <textarea class="form-control"></textarea> -->
                                    <input type="text" name="comment" class="form-control" onkeydown="if(event.keyCode==13){event.keyCode=0;event.returnValue=false;}">
                                </form>
                                <button type="button" class="btn btn-primary btn-sm send-button" ref="{{post.id}}" style="width: 25%">
                                    Comment
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
          </div>
        </article>
    {% endfor %}

    


    <!--pagination-->
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}

<script>
$(function() {
})

</script>
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootoast.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{{url_for('static', filename='jquery.js')}}"></script>
    <script src="{{url_for('static', filename='popper.js')}}"></script>
    <script src="{{url_for('static', filename='bootstrap.js')}}"></script>
    <script src="{{url_for('static', filename='bootoast.js')}}"></script>

</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
              <a class="nav-item nav-link" href="{{ url_for('main.settings') }}">Settings</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{url_for('users.user_posts', username=current_user.username)}}">
                    <img class="rounded-circle my-nav-img" src="{{ url_for('static',filename='profile_pics/' + current_user.image_file) }}">
                </a>
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>

        <div class="col-md-4">
          <div class="content-section">
            <h3>Sidebar</h3>
            {% if current_user.is_authenticated and sidebar_info %}
            <p class='text-muted'> 
                <ul class="list-group">
                    {% for item in sidebar_info %}
                    <li class="list-group-item list-group-item-light">{{item}}</li>
                    {% endfor %}
                </ul>
            </p>
            {% else %}
            <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">lively community</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                </ul>
            </p>
            {% endif %}

          </div>
        </div>

      </div>
    </main>


</body>

<script>
    console.log('testing start')
    let steel = document.getElementsByClassName('bg-steel')[0]
    let color = localStorage.getItem('color')
    if (color == null) {
        console.log('use default steel color (grey)')
    } else {
        steel.style.background = color
    }

$(function () {


    // 点赞
    $like_btns = $(".like") // 为了防止下面回调函数中的this指向错误;
    $like_btns.on('click', function () {

        $like_btn = $(this)
        $.ajax({
            type:"POST",
            url:'/like/' + $(this).attr('ref'),
            success: function(data) {
                // 还没点赞
                if (data.logged) {
                    if (!data.founded) {
                        notify("like one post !", "info")
                        $like_btn.children().html(data.count)
                    }
                    // 点过赞了
                    else {
                        notify("remove one like", "info")
                        $like_btn.children().html(data.count)
                    }
                }
                else {
                    notify("please log in first !", "danger")
                    $like_btn.children().html(data.count)
                }
                    

            },
            error: () => {
                notify("request error !", 'danger')
            }
        })
    })

    // 添加评论
    $(".send-button").on("click", function () {
        $post_id = $(this).attr('ref')
        if ( ! ($("#comment-form-"+$post_id).serialize().trim()=="comment=")) {
            $.ajax({
                type: "POST",
                url: '/make_comment/'+$post_id,
                data: $("#comment-form-"+$post_id).serialize(),
                success: function (item) {
                    if (item.logged) {
                        add_item(item)
                        notify("make a comment !", "info")
                    }
                    else {
                        notify("please login first !", "danger")
                    }
                },
                error: () => {
                    notify("request error !", 'danger')
                }
            })
        } else {
            notify('Don\'t make an empty comment !', 'danger')
        }
        $("input").val('')
    })

    // 加载帖子的评论
    $(".comment-btn").on("click", function () {
        $post_id = $(this).attr('ref')
        $.ajax({
            type: "GET",
            dataType: 'json',
            url: "/get_comments/"+$post_id,
            success: function (result) {
                $("#comment-list-"+$post_id).html("")
                console.log(result)
                result.data.forEach((item) => {
                    add_item(item)
                })
            },
            error: () => {
                notify("request error !", 'danger')
            }
        })
    })

    $("#remember_check").on("change", function () {
        if ($(this).prop('checked')) {
            notify("cookie is applied if remember login", 'warning')
        }
    })

    function add_item (item) {
        let filename ="profile_pics/" + item.img
        let container = $("<div class='comment-container'></div>")
        let header = $("<div class='comment-header'></div>")
        let profile_img = $(`<div><img class='rounded-circle comment-img' src='/static/profile_pics/${item.img}''><a href="/user/${item.username}">${item.username}</></div>`)
        header.append(profile_img)
        header.append($("<span class='comment-time'></span>").text(item.time))
        container.append(header)
        container.append($("<span class='comment-content'></span>").text(item.content))
        $("#comment-list-"+$post_id).append(container)
    }

    function notify (info, signal) {
        bootoast({
            message: info,
            type: signal,
            position: 'right-bottom'
        })
    }



})

</script>

</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input", id="remember_check") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>

        <div>
            <span class="btn btn-info like" ref="{{post.id}}">
                like
                <span id="like_count{{post.id}}" >{{post.likes}}</span>
            </span>
            
            <button type="button" class="btn btn-primary btn-info comment-btn" ref="{{post.id}}" data-toggle="modal" data-target="#modal{{post.id}}">
                Comments
            </button>
        
            <div class="modal fade" id="modal{{post.id}}" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="comment-list-{{post.id}}">
                        </div>
                        <div class="modal-footer">
                            <form style="width: 60%" id="comment-form-{{post.id}}">
                                <!-- <textarea class="form-control"></textarea> -->
                                <input type="text" name="comment" class="form-control" onkeydown="if(event.keyCode==13){event.keyCode=0;event.returnValue=false;}">
                            </form>
                            <button type="button" class="btn btn-primary btn-sm send-button" ref="{{post.id}}" style="width: 25%">
                                Comment
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        
        </div>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>


{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>

            <div>
                <span class="btn btn-info like" ref="{{post.id}}">
                    like
                    <span id="like_count{{post.id}}" >{{post.likes}}</span>
                </span>
                
                <button type="button" class="btn btn-primary btn-info comment-btn" ref="{{post.id}}" data-toggle="modal" data-target="#modal{{post.id}}">
                    Comments
                </button>
            
                <div class="modal fade" id="modal{{post.id}}" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body" id="comment-list-{{post.id}}">
                            </div>
                            <div class="modal-footer">
                                <form style="width: 60%" id="comment-form-{{post.id}}">
                                    <!-- <textarea class="form-control"></textarea> -->
                                    <input type="text" name="comment" class="form-control" onkeydown="if(event.keyCode==13){event.keyCode=0;event.returnValue=false;}">
                                </form>
                                <button type="button" class="btn btn-primary btn-sm send-button" ref="{{post.id}}" style="width: 25%">
                                    Comment
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            
            </div>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}